spring:
  application:
    name: seat-holding-service
  data:
    redis:
      host: 192.168.0.37
      port: 6379
  kafka:
    bootstrap-servers: 192.168.0.37:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

seat-holding:
  hold-ttl-seconds: 600
  max-holds-per-user: 4
  kafka:
    topic: seat-hold-events

waiting-queue:
  base-url: http://localhost:8080
  token:
    secret: "${WAITING_TOKEN_SECRET:0123456789abcdef0123456789abcdef}"

server:
  port: 8081